# Generated by Django 4.1 on 2022-08-23 03:41

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='core',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='core',
            name='like',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Like'),
        ),
    ]
