# Generated by Django 4.1 on 2022-08-25 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_core_image_core_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='core',
            old_name='like',
            new_name='likes',
        ),
    ]
